"""five

Revision ID: a56c30e182cc
Revises: e002975179d9
Create Date: 2025-05-09 23:54:04.552749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a56c30e182cc'
down_revision: Union[str, None] = 'e002975179d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ExpertProfile', sa.Column('region', sa.String(), nullable=True))
    op.drop_column('ExpertProfile', 'gu')
    op.drop_column('ExpertProfile', 'do')
    op.drop_column('ExpertProfile', 'dong')
    op.drop_column('ExpertProfile', 'si')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ExpertProfile', sa.Column('si', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('ExpertProfile', sa.Column('dong', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('ExpertProfile', sa.Column('do', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('ExpertProfile', sa.Column('gu', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('ExpertProfile', 'region')
    # ### end Alembic commands ###
