"""sec

Revision ID: a452c1e14412
Revises: 97d9ac9510ef
Create Date: 2025-05-09 21:32:06.093800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a452c1e14412'
down_revision: Union[str, None] = '97d9ac9510ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ExpertProfile', sa.Column('image', sa.Integer(), nullable=True))
    op.add_column('ExpertProfile', sa.Column('province', sa.String(), nullable=True))
    op.add_column('ExpertProfile', sa.Column('city', sa.String(), nullable=True))
    op.add_column('ExpertProfile', sa.Column('district', sa.String(), nullable=True))
    op.add_column('ExpertProfile', sa.Column('neighborhood', sa.String(), nullable=True))
    op.drop_index('ix_ExpertProfile_id', table_name='ExpertProfile')
    op.drop_constraint('ExpertProfile_expert_id_fkey', 'ExpertProfile', type_='foreignkey')
    op.create_foreign_key(None, 'ExpertProfile', 'User', ['id'], ['id'])
    op.drop_column('ExpertProfile', 'expert_id')
    op.drop_column('ExpertProfile', 'image_url')
    op.drop_index('ix_FarmerProfile_id', table_name='FarmerProfile')
    op.drop_constraint('FarmerProfile_farmer_id_fkey', 'FarmerProfile', type_='foreignkey')
    op.create_foreign_key(None, 'FarmerProfile', 'User', ['id'], ['id'])
    op.drop_column('FarmerProfile', 'farmer_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('FarmerProfile', sa.Column('farmer_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'FarmerProfile', type_='foreignkey')
    op.create_foreign_key('FarmerProfile_farmer_id_fkey', 'FarmerProfile', 'User', ['farmer_id'], ['id'])
    op.create_index('ix_FarmerProfile_id', 'FarmerProfile', ['id'], unique=False)
    op.add_column('ExpertProfile', sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('ExpertProfile', sa.Column('expert_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'ExpertProfile', type_='foreignkey')
    op.create_foreign_key('ExpertProfile_expert_id_fkey', 'ExpertProfile', 'User', ['expert_id'], ['id'])
    op.create_index('ix_ExpertProfile_id', 'ExpertProfile', ['id'], unique=False)
    op.drop_column('ExpertProfile', 'neighborhood')
    op.drop_column('ExpertProfile', 'district')
    op.drop_column('ExpertProfile', 'city')
    op.drop_column('ExpertProfile', 'province')
    op.drop_column('ExpertProfile', 'image')
    # ### end Alembic commands ###
