"""thi

Revision ID: b6093fbdf071
Revises: a452c1e14412
Create Date: 2025-05-09 21:45:04.337186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6093fbdf071'
down_revision: Union[str, None] = 'a452c1e14412'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ExpertProfile', sa.Column('do', sa.String(), nullable=True))
    op.add_column('ExpertProfile', sa.Column('si', sa.String(), nullable=True))
    op.add_column('ExpertProfile', sa.Column('gu', sa.String(), nullable=True))
    op.add_column('ExpertProfile', sa.Column('dong', sa.String(), nullable=True))
    op.drop_column('ExpertProfile', 'neighborhood')
    op.drop_column('ExpertProfile', 'district')
    op.drop_column('ExpertProfile', 'province')
    op.drop_column('ExpertProfile', 'city')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ExpertProfile', sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('ExpertProfile', sa.Column('province', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('ExpertProfile', sa.Column('district', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('ExpertProfile', sa.Column('neighborhood', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('ExpertProfile', 'dong')
    op.drop_column('ExpertProfile', 'gu')
    op.drop_column('ExpertProfile', 'si')
    op.drop_column('ExpertProfile', 'do')
    # ### end Alembic commands ###
