"""four

Revision ID: e002975179d9
Revises: b6093fbdf071
Create Date: 2025-05-09 22:22:14.015055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e002975179d9'
down_revision: Union[str, None] = 'b6093fbdf071'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ExpertProfile', sa.Column('title', sa.String(), nullable=True))
    op.add_column('ExpertProfile', sa.Column('price', sa.Integer(), nullable=True))
    op.add_column('ExpertProfile', sa.Column('introduction', sa.String(), nullable=True))
    op.add_column('Order', sa.Column('expert_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'Order', 'ExpertProfile', ['expert_id'], ['id'])
    op.drop_column('Order', 'service_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Order', sa.Column('service_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'Order', type_='foreignkey')
    op.drop_column('Order', 'expert_id')
    op.drop_column('ExpertProfile', 'introduction')
    op.drop_column('ExpertProfile', 'price')
    op.drop_column('ExpertProfile', 'title')
    # ### end Alembic commands ###
