"""six

Revision ID: 9f5e63def4bc
Revises: a56c30e182cc
Create Date: 2025-05-10 00:17:47.080753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f5e63def4bc'
down_revision: Union[str, None] = 'a56c30e182cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('FarmerProfile', sa.Column('introduction', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('FarmerProfile', 'introduction')
    # ### end Alembic commands ###
